// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVy9oNs4nYZGA-OwUi3SVgtPccL-5jTD0',
    appId: '1:531130332557:web:daf44cc114e31ecdc879c4',
    messagingSenderId: '531130332557',
    projectId: 'siademo-5dd73',
    authDomain: 'siademo-5dd73.firebaseapp.com',
    storageBucket: 'siademo-5dd73.appspot.com',
    measurementId: 'G-464CJ7ER62',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVy9oNs4nYZGA-OwUi3SVgtPccL-5jTD0',
    appId: '1:531130332557:web:61aed5b0d3df0df9c879c4',
    messagingSenderId: '531130332557',
    projectId: 'siademo-5dd73',
    authDomain: 'siademo-5dd73.firebaseapp.com',
    storageBucket: 'siademo-5dd73.appspot.com',
    measurementId: 'G-QK8BC9ZL3T',
  );
}
